language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django coverage coveralls --use-mirrors
  - pip install . --use-mirrors
branches:
  only:
    - master
script:
  - coverage run --source=permissionsx setup.py test
after_success:
  - coverage report --omit "permissionsx/tests/*,permissionsx/utils.py,permissionsx/settings.py" -m
  - coveralls
env:
  - DJANGO=1.4.8
  - DJANGO=1.5.4
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.8
    - python: 3.3
      env: DJANGO=1.4.8
