language: python
python:
  - 2.7
install:
  - pip install tox coverage coveralls django==1.6.3 django-debug-toolbar==1.1 django-tastypie==0.11.0 --use-mirrors
  - pip install .
branches:
  only:
    - master
script:
  - tox -e $TOX_ENV
after_success:
  - coverage erase
  - coverage run runtests.py
  - coverage report -m
  - coveralls
env:
  - TOX_ENV=pep8
  - TOX_ENV=py27-django-1.5.8
  - TOX_ENV=py27-django-1.6.5
  - TOX_ENV=py27-django-upcoming
  - TOX_ENV=py34-django-1.5.8
  - TOX_ENV=py34-django-1.6.5
  - TOX_ENV=py34-django-upcoming
