language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
  - python setup.py -q install
branches:
  only:
    - master
script:
  - python setup.py test
env:
  - DJANGO=1.4.8
  - DJANGO=1.5.4
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.8
    - python: 3.3
      env: DJANGO=1.4.8
