language: python
python:
  - 2.7
install:
  - pip install tox coverage coveralls django==1.6.2 django-debug-toolbar==1.0.1 django-tastypie==0.11.0 --use-mirrors
  - pip install .
branches:
  only:
    - master
script:
  - tox -e $TOX_ENV
after_success:
  - coverage erase
  - coverage run runtests.py
  - coverage report -m
  - coveralls
env:
  - TOX_ENV=pep8
  - TOX_ENV=py26-django1.5.5
  - TOX_ENV=py26-django1.6.2
  - TOX_ENV=py27-django1.5.5
  - TOX_ENV=py27-django1.6.2
  - TOX_ENV=py33-django1.5.5
  - TOX_ENV=py33-django1.6.2
